INSERT INTO pizzaer(nr, type, pris) VALUES ('1', 'Margarita', '45'); 
INSERT INTO pizzaer(nr, type, pris) VALUES ('2', 'Skinke', '50');
INSERT INTO pizzaer(nr, type, pris)  VALUES ('3', 'Pepperoni', '60');
INSERT INTO pizzaer(nr, type, pris) VALUES ('4', 'Carbonara', '55'); 
INSERT INTO pizzaer(nr, type, pris)  VALUES ('5', 'Silvia', '60');
INSERT INTO pizzaer(nr, type, pris)  VALUES ('6', 'Amerikaner', '69');
INSERT INTO pizzaer(nr, type, pris)  VALUES ('7', 'Bertil', '55');
INSERT INTO pizzaer(nr, type, pris)  VALUES ('8', 'Victoria', '50');
INSERT INTO pizzaer(nr, type, pris)  VALUES ('9', 'Mafia', '120');
INSERT INTO pizzaer(nr, type, pris)  VALUES ('10', 'Steve Jobs', '125');
INSERT INTO pizzaer(nr, type, pris)  VALUES ('11', 'Hval', '99');
INSERT INTO pizzaer(nr, type, pris)  VALUES ('12', 'Chili', '45');
INSERT INTO pizzaer(nr, type, pris)  VALUES ('13', 'Mario', '75');
INSERT INTO pizzaer(nr, type, pris)  VALUES ('14', 'Gollum', '25');
INSERT INTO pizzaer(nr, type, pris)  VALUES ('15', 'Potter', '85');